### ISSUE TITLE
[ONBOARDING] Apache ZooKeeper Official OCI Image

### ISSUE THREAD

**Issue by deusebio** [canonical/oci-factory#122]
### Image name

zookeeper-rock

### Short description

Apache ZooKeeper OCI Image from Canonical, based on Ubuntu.

### Image repository

https://github.com/canonical/zookeeper-rock

### Maintainer agreement

- [X] I agree to follow this project's [Code of Conduct](https://github.com/canonical/oci-factory/blob/main/CODE_OF_CONDUCT.md)
- [X] I understand and acknowledge the [CONTRIBUTING](https://github.com/canonical/oci-factory/blob/main/CONTRIBUTING.md) guidelines and [Image Maintainer Agreement](https://github.com/canonical/oci-factory/blob/main/IMAGE_MAINTAINER_AGREEMENT.md)

- [X] This image is a rock which already exists in the 'ubuntu' namespace

- [X] I agree to be the image's Maintainer and thus own it and be responsible for it, thus committing to maintaining it throughout its lifetime

- [X] My image's repository (where the build recipes are hosted) is public

- [X] I agree to have the provided contacts added to the Image Maintainers mailing list in Launchpad

- [ ] This image is meant to be published to the 'ubuntu' namespace, and thus a new registry repository should be created

- [X] I acknowledge that this image shall be monitored by the security team and that I've made the [necessary modifications](https://github.com/canonical/oci-factory/blob/main/IMAGE_MAINTAINER_AGREEMENT.md#enable-security-monitoring)
to support that

- [X] I commit to address image issues in a timely manner and according to their severity

- [X] I will always provide up-to-date documentation for this image
- [X] I understand the [OCI tagging convention](https://github.com/canonical/oci-factory/blob/main/IMAGE_MAINTAINER_AGREEMENT.md#acknowledge-the-oci-tagging-convention)

- [X] I understand the [image's stability commitments](https://github.com/canonical/oci-factory/blob/main/IMAGE_MAINTAINER_AGREEMENT.md#understand-the-ubuntu-rocks-stability-commitments)

- [X] I will test my image before proposing new build and releases

### Security enablement

packages: openjdk-8-jre-headless

We have enabled security monitoring on the image repo using trivy. The security scanning repository can be seen [here](https://github.com/canonical/zookeeper-rock/security/code-scanning) as long as people has the right permission to do so. 

### Primary contact

data-platform@lists.launchpad.net

**Comment by cjdcordeiro** [comment]
Great @deusebio ! 

So:
1. the repo already exists in DH and ECR, so this would effectively start pushing new tags which would be rocks! Awesome. Just pls make sure the docs reflect that -> https://github.com/canonical/oci-factory/pull/120#pullrequestreview-1865627700
2. I've added you to https://launchpad.net/~ubuntu-docker-images (your team was already there anyway)

Finally, there's just one thing missing:
 -[] yes, this image should already be monitored by the security team. However, the security team relies on a special manifest being added to the image, in order to scan it successfully. Can you please add it to your rock (the existing zookeeper docker image already has it) ([ref](https://github.com/canonical/oci-factory/blob/main/IMAGE_MAINTAINER_AGREEMENT.md#enable-security-monitoring))

**Comment by deusebio** [comment]
I have added the part to export the debs in this [PR](https://github.com/canonical/zookeeper-rock/pull/3). Not surprisingly (since I don't use extra debs in the rockcraft), the `dpkg-query` is empty. Also, unlike the original docker, I don't use snaps. 

Actually, the only relevant part is that we pull the artifacts (ZooKeeper is a Java product, hence made up of a bunch of jars) from a central repository [here](https://github.com/canonical/zookeeper-rock/blob/3-22.04/rockcraft.yaml#L45). We have setup a security scanning using trivy since the security team does not yet have a security scanning for java artifacts. 

Given this, how would you suggest to proceed for the security bits?

**Comment by cjdcordeiro** [comment]
> Not surprisingly (since I don't use extra debs in the rockcraft), the dpkg-query is empty. 

Yes, I think that's because the part exemplified in https://github.com/canonical/oci-factory/blob/main/IMAGE_MAINTAINER_AGREEMENT.md#enable-security-monitoring only works for packages that have been installed via `overlay-packages`.

In your case, it's just `openjdk-8-jre-headless` but it is installed via `stage-packages`, which doesn't leave a trace of it under `dpkg/status`. If you can't make that pkg be installed via `overlay-packages`, then never mind and we'll move 0ahead as is. Let me know

**Comment by cjdcordeiro** [comment]
Hi @deusebio . just checking back on this. If you can't make it work via the `overlay-packages` we'll proceed anyway. Let me know if I can help

**Comment by cjdcordeiro** [comment]
Cool! @deusebio at first glance, it looks ok! I can see the OpenJDK package both in the dpkg/status and the custom manifest :) `ii ,openjdk-8-jre-headless:amd64,8u392-ga-1~22.04,openjdk-8,8u392-ga-1~22.04`

Your recipe changes also look normal to me. I guess [this new line](https://github.com/canonical/zookeeper-rock/pull/3/commits/8cf67de66e27790de96f0c4bc655f10e0be4b25f#diff-67c464bbed217d3d422ddd2db32d89360c18ce8584542858e61f3f842c6fb432R52) is just to be safe?

**Comment by deusebio** [comment]
Uhm, good point! The Java linking [here](https://github.com/canonical/zookeeper-rock/pull/3/commits/8cf67de66e27790de96f0c4bc655f10e0be4b25f#diff-67c464bbed217d3d422ddd2db32d89360c18ce8584542858e61f3f842c6fb432R54) was failing with `File exists` error, since the linking is already done when installing the package on the overlay, which was not probably not the case when it was in `build`. I took these from the charmed zookeeper image, but it is probably not needed to redo the linking. 

I commented out the lines around the Java Linking, and it works just fine, but one hop more to `/etc/alternatives/java`, e.g. 

```
root@0907860904f6:/# which java
/usr/bin/java
root@0907860904f6:/# ls -l /usr/bin/java 
lrwxrwxrwx 1 root root 22 Mar  1 09:18 /usr/bin/java -> /etc/alternatives/java
root@0907860904f6:/# ls -l /etc/alternatives/java
lrwxrwxrwx 1 root root 46 Mar  1 09:18 /etc/alternatives/java -> /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
root@0907860904f6:/# java -version
openjdk version "1.8.0_392"
OpenJDK Runtime Environment (build 1.8.0_392-8u392-ga-1~22.04-b08)
OpenJDK 64-Bit Server VM (build 25.392-b08, mixed mode)
root@0907860904f6:/# 
```

**Comment by cjdcordeiro** [comment]
Cool! In any case, the security team has been contacted and all looks alright for the onboarding. Thanks. Closing this ticket
