### ISSUE TITLE
[ONBOARDING] Python

### ISSUE THREAD

**Issue by rebornplusplus** [canonical/oci-factory#124]
### Image name

python

### Short description

This is a Python rock, useful for running Python applications

### Image repository

https://github.com/canonical/chiselled-python

### Maintainer agreement

- [X] I agree to follow this project's [Code of Conduct](https://github.com/canonical/oci-factory/blob/main/CODE_OF_CONDUCT.md)
- [X] I understand and acknowledge the [CONTRIBUTING](https://github.com/canonical/oci-factory/blob/main/CONTRIBUTING.md) guidelines and [Image Maintainer Agreement](https://github.com/canonical/oci-factory/blob/main/IMAGE_MAINTAINER_AGREEMENT.md)

- [ ] This image is a rock which already exists in the 'ubuntu' namespace

- [X] I agree to be the image's Maintainer and thus own it and be responsible for it, thus committing to maintaining it throughout its lifetime

- [X] My image's repository (where the build recipes are hosted) is public

- [X] I agree to have the provided contacts added to the Image Maintainers mailing list in Launchpad

- [ ] This image is meant to be published to the 'ubuntu' namespace, and thus a new registry repository should be created

- [ ] I acknowledge that this image shall be monitored by the security team and that I've made the [necessary modifications](https://github.com/canonical/oci-factory/blob/main/IMAGE_MAINTAINER_AGREEMENT.md#enable-security-monitoring)
to support that

- [X] I commit to address image issues in a timely manner and according to their severity

- [X] I will always provide up-to-date documentation for this image
- [X] I understand the [OCI tagging convention](https://github.com/canonical/oci-factory/blob/main/IMAGE_MAINTAINER_AGREEMENT.md#acknowledge-the-oci-tagging-convention)

- [X] I understand the [image's stability commitments](https://github.com/canonical/oci-factory/blob/main/IMAGE_MAINTAINER_AGREEMENT.md#understand-the-ubuntu-rocks-stability-commitments)

- [X] I will test my image before proposing new build and releases

### Security enablement

- base-files
- libgcc-s1
- libc6
- openssl
- ca-certificates
- ncurses-base
- python3.8

### Primary contact

rocks-dev@lists.canonical.com

**Comment by cjdcordeiro** [comment]
Since this is a chiselled rock, we can open an exception to the lack of `/usr/share/rocks/dpkg.query` file - please untick that box above.

The repos have been created in both DH and ECR
