### ISSUE TITLE
[ONBOARDING] Kafka slim image

### ISSUE THREAD

**Issue by deusebio** [canonical/oci-factory#154]
### Image name

kafka

### Short description

Apache Kafka Rock Image based on Ubuntu. Apache Kafka is an open-source distributed event streaming platform for high-performance data pipelines, streaming analytics and integrations. This image also requires the Apache ZooKeeper image to run.

### Image repository

https://github.com/canonical/kafka-rock

### Maintainer agreement

- [X] I agree to follow this project's [Code of Conduct](https://github.com/canonical/oci-factory/blob/main/CODE_OF_CONDUCT.md)
- [X] I understand and acknowledge the [CONTRIBUTING](https://github.com/canonical/oci-factory/blob/main/CONTRIBUTING.md) guidelines and [Image Maintainer Agreement](https://github.com/canonical/oci-factory/blob/main/IMAGE_MAINTAINER_AGREEMENT.md)

- [X] This image is a rock which already exists in the 'ubuntu' namespace

- [X] I agree to be the image's Maintainer and thus own it and be responsible for it, thus committing to maintaining it throughout its lifetime

- [X] My image's repository (where the build recipes are hosted) is public

- [X] I agree to have the provided contacts added to the Image Maintainers mailing list in Launchpad

- [ ] This image is meant to be published to the 'ubuntu' namespace, and thus a new registry repository should be created

- [X] I acknowledge that this image shall be monitored by the security team and that I've made the [necessary modifications](https://github.com/canonical/oci-factory/blob/main/IMAGE_MAINTAINER_AGREEMENT.md#enable-security-monitoring)
to support that

- [X] I commit to address image issues in a timely manner and according to their severity

- [X] I will always provide up-to-date documentation for this image
- [X] I understand the [OCI tagging convention](https://github.com/canonical/oci-factory/blob/main/IMAGE_MAINTAINER_AGREEMENT.md#acknowledge-the-oci-tagging-convention)

- [X] I understand the [image's stability commitments](https://github.com/canonical/oci-factory/blob/main/IMAGE_MAINTAINER_AGREEMENT.md#understand-the-ubuntu-rocks-stability-commitments)

- [X] I will test my image before proposing new build and releases

### Primary contact

data-platform@lists.launchpad.net

**Comment by cjdcordeiro** [comment]
cool! All good on the deb monitoring side?

**Comment by deusebio** [comment]
Yes, we are just waiting final confirmation from emitorino . I have added you to the thread, so you can be up to date

**Comment by cjdcordeiro** [comment]
Got a reply. all seems good!
