### ISSUE TITLE
[ONBOARDING] Admin UI

### ISSUE THREAD

**Issue by shipperizer** [canonical/oci-factory#259]
### Image name

identity-platform-admin-ui

### Short description

Canonical Admin UI is a component to manage the Canonical Identity Platform 

### Image repository

https://github.com/canonical/identity-platform-admin-ui

### Maintainer agreement

- [X] I agree to follow this project's [Code of Conduct](https://github.com/canonical/oci-factory/blob/main/CODE_OF_CONDUCT.md)
- [X] I understand and acknowledge the [CONTRIBUTING](https://github.com/canonical/oci-factory/blob/main/CONTRIBUTING.md) guidelines and [Image Maintainer Agreement](https://github.com/canonical/oci-factory/blob/main/IMAGE_MAINTAINER_AGREEMENT.md)

- [ ] This image is a rock which already exists in the 'ubuntu' namespace

- [X] I agree to be the image's Maintainer and thus own it and be responsible for it, thus committing to maintaining it throughout its lifetime

- [X] My image's repository (where the build recipes are hosted) is public

- [X] I agree to have the provided contacts added to the Image Maintainers mailing list in Launchpad

- [X] This image is meant to be published to the 'ubuntu' namespace, and thus a new registry repository should be created

- [ ] I acknowledge that this image shall be monitored by the security team and that I've made the [necessary modifications](https://github.com/canonical/oci-factory/blob/main/IMAGE_MAINTAINER_AGREEMENT.md#enable-security-monitoring)
to support that

- [X] I commit to address image issues in a timely manner and according to their severity

- [X] I will always provide up-to-date documentation for this image
- [X] I understand the [OCI tagging convention](https://github.com/canonical/oci-factory/blob/main/IMAGE_MAINTAINER_AGREEMENT.md#acknowledge-the-oci-tagging-convention)

- [X] I understand the [image's stability commitments](https://github.com/canonical/oci-factory/blob/main/IMAGE_MAINTAINER_AGREEMENT.md#understand-the-ubuntu-rocks-stability-commitments)

- [X] I will test my image before proposing new build and releases

### Security enablement

deb packages:

* `ca-certificates`

### Primary contact

identity@lists.canonical.com

**Comment by cjdcordeiro** [comment]
@shipperizer is this a general purpose image? I.e. can I use it outside a charm? 
You've also left the security box unticked - is that a mishap?

**Comment by shipperizer** [comment]
@cjdcordeiro technically yes, but it is our internal application so it wouldn't make much sense used in isolation

re security, i m on it, so cannot tick it yet

**Comment by cjdcordeiro** [comment]
@shipperizer thanks for the info.

So let's try to understand this. Have the following been met?
 - despite being an internal application, any user should be able to pull this image (plus some other images if needed), and deploy it in their own Docker machine/Docker Swarm cluster/K8s cluster
 - from a Product perspective, publishing this image for public consumption via docker hub and ECR, has been agreed

**Comment by shipperizer** [comment]
1. yes
2. never touched the subject really, although repo is public so shouldn't be a problem

let me ask around and i ll get back to you

**Comment by cjdcordeiro** [comment]
(feel free to close it once the missing security box is ticked)
