### ISSUE TITLE
[ONBOARDING] Metrics-Proxy

### ISSUE THREAD

**Issue by IbraAoad** [canonical/oci-factory#268]
### Image name

metrics-proxy

### Short description

A lightweight proxy designed to expose a unified metrics endpoint for multiple Kubernetes pods.

### Image repository

https://github.com/canonical/metrics-proxy-rock

### Maintainer agreement

- [X] I agree to follow this project's [Code of Conduct](https://github.com/canonical/oci-factory/blob/main/CODE_OF_CONDUCT.md)
- [X] I understand and acknowledge the [CONTRIBUTING](https://github.com/canonical/oci-factory/blob/main/CONTRIBUTING.md) guidelines and [Image Maintainer Agreement](https://github.com/canonical/oci-factory/blob/main/IMAGE_MAINTAINER_AGREEMENT.md)

- [ ] This image is a rock which already exists in the 'ubuntu' namespace

- [X] I agree to be the image's Maintainer and thus own it and be responsible for it, thus committing to maintaining it throughout its lifetime

- [X] My image's repository (where the build recipes are hosted) is public

- [X] I agree to have the provided contacts added to the Image Maintainers mailing list in Launchpad

- [X] This image is meant to be published to the 'ubuntu' namespace, and thus a new registry repository should be created

- [X] I acknowledge that this image shall be monitored by the security team and that I've made the [necessary modifications](https://github.com/canonical/oci-factory/blob/main/IMAGE_MAINTAINER_AGREEMENT.md#enable-security-monitoring)
to support that

- [X] I commit to address image issues in a timely manner and according to their severity

- [X] I will always provide up-to-date documentation for this image
- [X] I understand the [OCI tagging convention](https://github.com/canonical/oci-factory/blob/main/IMAGE_MAINTAINER_AGREEMENT.md#acknowledge-the-oci-tagging-convention)

- [X] I understand the [image's stability commitments](https://github.com/canonical/oci-factory/blob/main/IMAGE_MAINTAINER_AGREEMENT.md#understand-the-ubuntu-rocks-stability-commitments)

- [X] I will test my image before proposing new build and releases

### Security enablement

The `ca-certificates` package, similarly to all of the Observability rocks; as already discussed for those ones, it's added to the security manifest.

### Primary contact

observability@lists.launchpad.net

**Comment by cjdcordeiro** [comment]
Nice. Thanks @IbraAoad . I shall be all good, but have you notified the security team about this new image?

**Comment by IbraAoad** [comment]
> Nice. Thanks @IbraAoad . I shall be all good, but have you notified the security team about this new image?

Hey @cjdcordeiro , I've notified them and you're looped in the email, any idea what to do next?

**Comment by cjdcordeiro** [comment]
You're all good @IbraAoad . Your team is already on the mailing list. 
And I've just created the 2 repos in DH and ECR. So you can proceed with the build requests ;)
