### ISSUE TITLE
[ONBOARDING] OpenSearch

### ISSUE THREAD

**Issue by Mehdi-Bendriss** [canonical/oci-factory#33]
### Image name

charmed-opensearch

### Image repository

https://github.com/canonical/charmed-opensearch-rock

### Image type

ROCK

### Maintainer agreement

- [X] I agree to follow this project's [Code of Conduct](https://github.com/canonical/oci-factory/blob/main/CODE_OF_CONDUCT.md)
- [X] I understand and acknowledge the [CONTRIBUTING](https://github.com/canonical/oci-factory/blob/main/CONTRIBUTING.md) guidelines and [Image Maintainer Agreement](https://github.com/canonical/oci-factory/blob/main/IMAGE_MAINTAINER_AGREEMENT.md)

- [X] This image is either a ROCK or a Docker image which already exists in the 'ubuntu' namespace

- [X] I agree to be the image's Maintainer and thus own it and be responsible for it, thus committing to maintaining it throughout its lifetime

- [X] My image's repository (where the build recipes are hosted) is public

- [X] I agree to have the provided contacts added to the Image Maintainers mailing list in Launchpad

- [X] This image is meant to be published to the 'ubuntu' namespace, and thus a new registry repository should be created

- [X] I acknowledge that this image shall be monitored by the security team and that I've made the [necessary modifications](https://github.com/canonical/oci-factory/blob/main/IMAGE_MAINTAINER_AGREEMENT.md#enable-security-monitoring)
to support that

- [X] I commit to address image issues in a timely manner and according to their severity

- [X] I will always provide up-to-date documentation for this image
- [X] I understand the [OCI tagging convention](https://github.com/canonical/oci-factory/blob/main/IMAGE_MAINTAINER_AGREEMENT.md#acknowledge-the-oci-tagging-convention)

- [X] I understand the [image's stability commitments](https://github.com/canonical/oci-factory/blob/main/IMAGE_MAINTAINER_AGREEMENT.md#understand-the-ubuntu-rocks-stability-commitments)

- [X] I will test my image before proposing new build and releases

### Primary contact

data-platform@lists.launchpad.net

**Comment by cjdcordeiro** [comment]
Great! thank you @Mehdi-Bendriss . You left the `Security enablement` section empty though. Can you please add a ref/link to the thread where you're handling with @metorino ?

**Comment by cjdcordeiro** [comment]
All of this seems to have been checked out and @metorino is already aware of this new image. Closing the issue.

**Comment by metorino** [comment]
@cjdcordeiro FYI this new image has been added to the security monitoring service.
