### ISSUE TITLE
[ONBOARDING] alertmanager

### ISSUE THREAD

**Issue by lucabello** [canonical/oci-factory#42]
### Image name

alertmanager

### Image repository

https://github.com/canonical/alertmanager-rock

### Image type

ROCK

### Maintainer agreement

- [X] I agree to follow this project's [Code of Conduct](https://github.com/canonical/oci-factory/blob/main/CODE_OF_CONDUCT.md)
- [X] I understand and acknowledge the [CONTRIBUTING](https://github.com/canonical/oci-factory/blob/main/CONTRIBUTING.md) guidelines and [Image Maintainer Agreement](https://github.com/canonical/oci-factory/blob/main/IMAGE_MAINTAINER_AGREEMENT.md)

- [X] This image is either a ROCK or a Docker image which already exists in the 'ubuntu' namespace

- [X] I agree to be the image's Maintainer and thus own it and be responsible for it, thus committing to maintaining it throughout its lifetime

- [X] My image's repository (where the build recipes are hosted) is public

- [X] I agree to have the provided contacts added to the Image Maintainers mailing list in Launchpad

- [X] This image is meant to be published to the 'ubuntu' namespace, and thus a new registry repository should be created

- [X] I acknowledge that this image shall be monitored by the security team and that I've made the [necessary modifications](https://github.com/canonical/oci-factory/blob/main/IMAGE_MAINTAINER_AGREEMENT.md#enable-security-monitoring)
to support that

- [X] I commit to address image issues in a timely manner and according to their severity

- [X] I will always provide up-to-date documentation for this image
- [X] I understand the [OCI tagging convention](https://github.com/canonical/oci-factory/blob/main/IMAGE_MAINTAINER_AGREEMENT.md#acknowledge-the-oci-tagging-convention)

- [X] I understand the [image's stability commitments](https://github.com/canonical/oci-factory/blob/main/IMAGE_MAINTAINER_AGREEMENT.md#understand-the-ubuntu-rocks-stability-commitments)

- [X] I will test my image before proposing new build and releases

### Security enablement

This has already been discussed and approved, but here's the upstream project of the ROCK: https://github.com/prometheus/alertmanager.

### Primary contact

observability@lists.launchpad.net

**Comment by lucabello** [comment]
Please note the **alertmanager** image repository has not been created yet; there is an existing one called **prometheus-alertmanager** (currently hosting a Dockerfile-based old image) that, as discussed separately, should be deprecated in favor of the new repository.

**Comment by lucabello** [comment]
**Description**: The Alertmanager handles alerts sent by client application such as the   Prometheus server. It takes care of deduplicating, grouping, and routing them to the correct receiver integrations such as email, PagerDuty, OpSGenie, or many other mechanisms thanks to the webhook receiver. It also takes care of silencing and inhibition of alerts.

**Comment by cjdcordeiro** [comment]
Right, this one needs a bit more love :)

I've created: 
 - https://hub.docker.com/r/ubuntu/alertmanager
 - https://gallery.ecr.aws/ubuntu/alertmanager

I have added a 301 note to the existing `prometheus-alertmanager` repos:
 - https://gallery.ecr.aws/ubuntu/prometheus-alertmanager
 - https://hub.docker.com/r/ubuntu/prometheus-alertmanager

Please make sure not to push any more images to the old `prometheus-alertmanager` repo. 

(FYI @metorino)
